# 5. Python Homework

# 1. What does Pandas stand for?

- The name Pandas comes from panel data and is used to describe data sets and analize them. Is a library of Python. 

# 2. What are the 2 collections used in Pandas?

- Series
- DataFrame

# 3. Name 4 things Pandas can do for us.
- Data Cleaning
- Data Analysis
- Data Transformation
- Data Input and Output


# 4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
- x = df.sort_value(by = ?, inplace=true?)

# 5. What is a CSV
-  Is a plain text file formated by comma separated values.

# 6. When cleaning data what values do we not like in our data?
- Null

# CODING EXERCISES

In [6]:
# 1. Concatenate these 3 arrays into a new array named 'newArray'...

import numpy as np

array1 = np.array ([[25, 16]])
array2 = np.array ([[11, 2], [13, 4]])
array3 = np.array ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate([array1, array2, array3])
print (newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [9]:
#2. Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)

print(sortedArray)


[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [20]:
#3 Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.

reshapedArray = np.arange(6).reshape((2, 3)) #why double parenthesis, using the curriculum as reference 4.2
print(reshapedArray)

[[0 1 2]
 [3 4 5]]


In [23]:
#4. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

a, b = reshapedArray
a1, a2, a3 = a

print(a)
print(b)
print(a1, a2, a3)

# idk if this makes sense I am following the curriculum at this
# point, I know is asking me for 4 but couldn't get it right


[0 1 2]
[3 4 5]
0 1 2


In [28]:
# 5. Combined and sort the following arrays into one called 'comboArray

import numpy as np

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three)) #why the parenthesis 2 times? If I do one
# gives me an error that it cannot be interpret as an interger or something. Need clarification por favor :S

print (comboArray)

[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]


In [45]:
# 6.Take 'comboArray' and perform the following slicing activities:

import numpy as np

checkingthelength = len(comboArray)
print (checkingthelength)

print(comboArray [1])
print(comboArray [2: ])
print(comboArray [3:15])
print(comboArray [-6:])
print(comboArray [-17:-1]) #?
print(comboArray [0::2]) #?
print(comboArray [-1::5]) #? 

24
11
[12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
[13 14 15 16 17 20 21 22 23 24 25 26]
[2 3 4 5 6 7]
[17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6]
[10 12 14 16 20 22 24 26  0  2  4  6]
[7]


In [49]:
import numpy as np

array4 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

array5 = np.array([[17.0, 70.0, 10.7]])

print ((array4*array5))
print ((array4+array5))
print ((array4/array5))



[[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1.08500e+03 2.72850e+02]]]
[[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]
[[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]


In [50]:
#8. Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in pont #7

import numpy as np

subtraction = np.subtract(array4, array5)

print(subtraction)

[[[-17.   -70.   -10.6 ]
  [ -7.   -59.7   -0.69]]

 [[  3.   -49.98   9.4 ]
  [ 13.   -39.    19.6 ]]

 [[ 23.4  -46.    29.3 ]
  [ -2.   -54.5   14.8 ]]]


In [58]:
#9. Using modulo find all elements that are divisible by 3 from the multi-dimensional array under point #7 above.
import numpy as np


divisible_by_3 = array4[array4 % 3 == 0], array5[array5 % 3 == 0]#no clue...

print(divisible_by_3)


(array([ 0.,  0., 30., 24., 15.]), array([], dtype=float64))


#10. Using Series, create a DataFrame that looks like this:

Ingredients	Quantity	Unit
Flour	4	cups
Milk	1	cup
Eggs	2	large
Spam	1	can
Name: Dinner, dtype: object

In [62]:
import pandas as pd

Ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name='Ingridients')
Quantity = pd.Series([4, 1, 2, 1], name='Quantity')
Unit = pd.Series(['cups', 'cup', 'large', 'can'], name='Unit')

Dinner = pd.concat([Ingredients, Quantity, Unit], axis=1)

print(Dinner)

  Ingridients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [68]:
# #11.Take this data and create a DataFrame named studentData

# import pandas as pd

# Names = pd.Series(['Jai', 'Janusha', 'Gaurav', 'Anuj'], name = 'Name')
# Height = pd.Series([5.1, 6.2, 5.1, 5.2], name = 'Height')
# Qualification = pd.Series (['Msc', 'MA', 'Msc', 'Msc'], name = 'Qualification')
# Address = pd.Series(['Delhi', 'Doha', 'Chennai', 'Dakhar'], name = 'Address')
# Age = pd.Series([21, 23, 24, 21], name = 'Age')
# Pets = pd.Series(['Dog', 'Bunny', 'Chinchilla', 'Parrot'], name = 'Pets')
# Sport = pd.Series(['Darts', 'Basketball', 'PaddleBoarding', 'Cricket'], name = "Sports")

# StudentData = pd.concat([Names, Height, Qualification, Address, Age, Pets, Sport], axis=1)

# print(StudentData)

# # {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
# #         'Height': [5.1, 6.2, 5.1, 5.2],
# #         'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
# #         'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
# #         'Age': [21, 23, 24, 21],
# #         'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
# #         'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
# #     }

#whoops, in the curriculum there is a dataframe section redoing, just don't want to delete for my future reference 

import pandas as pd

info = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }

StudentData = pd.DataFrame(info)

print (StudentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [74]:
# 12. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

Desserts = pd.Series(["Ice cream", "Cashew Fudge", "Waffels", "Carrot Halwa"], name = 'Desserts')

# StudentData.insert(Desserts, name = 'Desserts', axis=1)

# print(StudentData)

StudentData['Desserts'] = Desserts

print(StudentData)

      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

       Desserts  
0     Ice cream  
1  Cashew Fudge  
2       Waffels  
3  Carrot Halwa  


In [79]:
#13. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

StudentData.sort_values(by = ['Name', 'address'], inplace = True)

# StudentData.sort_values(by = ['address'], inplace = True)

# i think my code is right but is not sorting the addresses....HEEEELP! MY BrAiNssss hurts :(

print(StudentData)

      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

       Desserts  
3  Carrot Halwa  
2       Waffels  
0     Ice cream  
1  Cashew Fudge  


In [80]:
# 14.Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df.to_csv('cows_and_goats.csv')



In [85]:
#15. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

#A

info2 = {'Vegetable': ['Lettuce', 'Tomato', 'Onion'],
         'In a Hamburger': ['Yes', 'Maybe', 'NoPeNope'], 
         'In a Salad': ['Yes', 'Yes', 'No']
         }
Vegetables = pd.DataFrame(info2)

print (Vegetables)

Vegetables.to_csv('Vegetables.csv') #DONE

#B

VegetablesCopy = pd.read_csv('Vegetables.csv')
VegetablesCopy.sort_values(by = ["Vegetable"], inplace=True)

VegetablesCopy.to_csv('VegetablesCopy.csv')




  Vegetable In a Hamburger In a Salad
0   Lettuce            Yes        Yes
1    Tomato          Maybe        Yes
2     Onion       NoPeNope         No
