# 5. Python Homework

# 1. What does Pandas stand for?

- The name Pandas comes from panel data and is used to describe data sets and analize them. Is a library of Python. 

# 2. What are the 2 collections used in Pandas?

- Series
- DataFrame

# 3. Name 4 things Pandas can do for us.
- Data Cleaning
- Data Analysis
- Data Transformation
- Data Input and Output


# 4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
- x = df.sort_value(by = ?, inplace=true?)

# 5. What is a CSV
-  Is a plain text file formated by comma separated values.

# 6. When cleaning data what values do we not like in our data?
- Null

# CODING EXERCISES

In [6]:
# 1. Concatenate these 3 arrays into a new array named 'newArray'...

import numpy as np

array1 = np.array ([[25, 16]])
array2 = np.array ([[11, 2], [13, 4]])
array3 = np.array ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate([array1, array2, array3])
print (newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [9]:
#2. Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)

print(sortedArray)


[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [20]:
#3 Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.

reshapedArray = np.arange(6).reshape((2, 3)) #why double parenthesis, using the curriculum as reference 4.2
print(reshapedArray)

[[0 1 2]
 [3 4 5]]


In [23]:
#4. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

a, b = reshapedArray
a1, a2, a3 = a

print(a)
print(b)
print(a1, a2, a3)

# idk if this makes sense I am following thee curriculum at this
# point, I know it asked me for 4 but just messing with the code 
# to further understand it by doing it. 


[0 1 2]
[3 4 5]
0 1 2


In [28]:
# 5. Combined and sort the following arrays into one called 'comboArray

import numpy as np

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three)) #why the parenthesis 2 times? If I do one
#gives me an error that it cannot be interpret as an interger or something. Need clarification por favor :S

print (comboArray)

[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]


In [45]:
# 6.Take 'comboArray' and perform the following slicing activities:

import numpy as np

checkingthelength = len(comboArray)
print (checkingthelength)

print(comboArray [1])
print(comboArray [2: ])
print(comboArray [3:15])
print(comboArray [-6:])
print(comboArray [-17:-1]) #?
print(comboArray [0::2]) #?
print(comboArray [-1::5]) #? 

24
11
[12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
[13 14 15 16 17 20 21 22 23 24 25 26]
[2 3 4 5 6 7]
[17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6]
[10 12 14 16 20 22 24 26  0  2  4  6]
[7]


In [49]:
import numpy as np

array4 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

array5 = np.array([[17.0, 70.0, 10.7]])

print ((array4*array5))
print ((array4+array5))
print ((array4/array5))



[[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1.08500e+03 2.72850e+02]]]
[[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]
[[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]


In [50]:
#8. Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in pont #7

import numpy as np

subtraction = np.subtract(array4, array5)

print(subtraction)

[[[-17.   -70.   -10.6 ]
  [ -7.   -59.7   -0.69]]

 [[  3.   -49.98   9.4 ]
  [ 13.   -39.    19.6 ]]

 [[ 23.4  -46.    29.3 ]
  [ -2.   -54.5   14.8 ]]]


In [58]:
#9. Using modulo find all elements that are divisible by 3 from the multi-dimensional array under point #7 above.
import numpy as np


divisible_by_3 = array4[array4 % 3 == 0], array5[array5 % 3 == 0]#no clue...

print(divisible_by_3)


(array([ 0.,  0., 30., 24., 15.]), array([], dtype=float64))
